apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  selector:
    app: mysql #selects pod that has the nginx label
  type: LoadBalancer # For external activity, the other option is ClusterIP for internal load balancing. 
  ports: 
    - name: http
      protocol: TCP 
      port: 3306
      targetPort: 3306