apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    app: nginx #selects pod that has the nginx label
  type: LoadBalancer # For external activity, the other option is ClusterIP for internal load balancing. 
  ports: 
    - name: http
      protocol: TCP 
      port: 80
      targetPort: 80